server:
  port: 8080

eureka:
  client:
    enabled: false

spring:
  config:
    on-profile: prod
  application:
    name: product-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/ordermsa
    username: admin
    password: ${DB_PW}
    hikari: 
      maximum-pool-size: 1
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  kafka:
    kafka-server: kafka-service:9092
    consumer:
      # group-id는 컨슈머 그룹을 식별하는 ID로서 동일한 그룹ID를 가진 컨슈머들은 메시지를 분담해서 consume
      # 그런데 만약 컨슈머가 더로 다른 group-id를 가지고 한 topic을 consume하면 메시지를 각기 수신하는 pub/sub효과 발생
      group-id: product-group
      # 가장 처음 들어온 메시지부터 읽기 시작(latest: 현시점 이후로 들어오는 메시지만 읽음)
      auto-offset-reset: earliest
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

cloud:
  aws:
    credentials:
      access-key: xxxx
      secret-key: yyyy
    region:
      static: ap-northeast-2
    s3:
      bucket: crongs-order
